-- Migration: Create blog_assets and blog_post_likes tables
-- This fixes PGRST205 errors: 'blog_assets' not found in schema cache

-- 1. Create Media Manager Assets Table
CREATE TABLE IF NOT EXISTS public.blog_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID, -- References users(id) but can be any UUID for flexible role management
    filename TEXT NOT NULL,
    url TEXT NOT NULL,
    mimetype TEXT,
    size BIGINT,
    asset_type TEXT DEFAULT 'user_upload',
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- 2. Create Blog Post Likes Table
CREATE TABLE IF NOT EXISTS public.blog_post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id UUID REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(post_id, fingerprint)
);

-- 3. Enable RLS
ALTER TABLE public.blog_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_post_likes ENABLE ROW LEVEL SECURITY;

-- 4. Policies for blog_assets
DROP POLICY IF EXISTS "Assets viewable by everyone" ON public.blog_assets;
CREATE POLICY "Assets viewable by everyone" ON public.blog_assets FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can manage own assets" ON public.blog_assets;
CREATE POLICY "Users can manage own assets" ON public.blog_assets FOR ALL USING (auth.uid()::text = user_id::text);

-- 5. Policies for blog_post_likes
DROP POLICY IF EXISTS "Anyone can like" ON public.blog_post_likes;
CREATE POLICY "Anyone can like" ON public.blog_post_likes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can view likes" ON public.blog_post_likes;
CREATE POLICY "Anyone can view likes" ON public.blog_post_likes FOR SELECT USING (true);

-- 6. Add missing stats columns to blog_posts if they don't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'blog_posts' AND column_name = 'views_count') THEN
        ALTER TABLE public.blog_posts ADD COLUMN views_count INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'blog_posts' AND column_name = 'likes_count') THEN
        ALTER TABLE public.blog_posts ADD COLUMN likes_count INTEGER DEFAULT 0;
    END IF;
END $$;

-- 7. Refresh PostgREST cache
NOTIFY pgrst, 'reload schema';
